"use strict";
const $=id=>document.getElementById(id),KEY='staemmeCoachStateV5';let state;
const fmt=v=>Number.isFinite(v)?v.toLocaleString('de-DE'):'–';
const dur=s=>{s=Math.max(0,Math.round(s||0));return `${Math.floor(s/3600)} Std. ${Math.floor((s%3600)/60)} Min.`};
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))}catch{return null}},save=v=>{state=v;localStorage.setItem(KEY,JSON.stringify(v));render()};
const qSecs=()=> (state.buildQueue||[]).reduce((a,x)=>a+(+x.remainingSeconds||0),0);
function levels(){const e={...(state.buildings||{})};for(const x of state.buildQueue||[])if(Number.isFinite(x.targetLevel))e[x.building]=Math.max(e[x.building]||0,x.targetLevel);return e}
function buildRec(){const e=levels(),snob=(e.Adelshof||0)>=1;if(!snob){if((e.Hauptgebäude||0)<20)return [`Hauptgebäude ${(e.Hauptgebäude||0)+1}`,'beschleunigt den weiteren Ausbau'];if((e.Schmiede||0)<10)return [`Schmiede ${(e.Schmiede||0)+1}`,'Voraussetzung für den Adelshof'];if((e.Marktplatz||0)<10)return [`Marktplatz ${(e.Marktplatz||0)+1}`,'Voraussetzung für den Adelshof']}for(const [n,t,r] of [['Eisenmine',25,'mehr Eisen für LK und Adel'],['Speicher',20,'Reserve für teure Ausbauten'],['Bauernhof',18,'mehr Platz für die OFF-Armee'],['Stall',10,'schnellere LK-Produktion'],['Schmiede',10,'Forschung weiter ausbauen'],['Holzfäller',25,'Rohstoffversorgung steigern'],['Lehmgrube',25,'Rohstoffversorgung steigern']])if((e[n]||0)<t)return [`${n} ${(e[n]||0)+1}`,r];return [`Bauernhof ${(e.Bauernhof||0)+1}`,'mehr Platz für die OFF-Armee']}
function troopRec(){const u=state.units||{},r=state.resources||{},free=Number.isFinite(state.population?.current)&&Number.isFinite(state.population?.max)?state.population.max-state.population.current:null;if(free!==null&&free<20)return ['Bauernhof zuerst',`nur ${free} freie Bevölkerung`];if((u.light||0)<100&&r.wood>=625&&r.clay>=500&&r.iron>=1250)return ['5 Leichte Kavallerie','OFF-Dorf: Mobilität und Farmleistung'];if((u.axe||0)<500&&r.wood>=600&&r.clay>=300&&r.iron>=400)return ['10 Axtkämpfer','OFF-Grundmasse ausbauen'];if((u.spear||0)<100)return [`${Math.min(10,100-(u.spear||0))} Speerträger`,'kleine Grundabsicherung'];return ['Rohstoffe ansparen','für Axtkämpfer oder Leichte Kavallerie']}
function status(){const c=state.completeness||{},items=[['Dorf',c.village],['Rohstoffe',c.resources],['Bevölkerung',c.population],['Produktion',c.production],['Gebäude',c.buildings],['Bauschleife',c.buildQueue],['Truppen',c.units],['Effekte',c.effects]],missing=items.filter(x=>!x[1]),box=$('dataStatus');box.className='status '+(missing.length?'bad':'good');box.innerHTML=missing.length?`<strong>⚠ Spieldaten teilweise unvollständig</strong><br>${missing.map(x=>'✗ '+x[0]).join(' · ')}`:'<strong>✓ Alle wichtigen Bereiche vollständig</strong>';$('statusDetails').innerHTML=items.map(x=>`<div class="${x[1]?'ok':'missing'}">${x[1]?'✓':'✗'} ${x[0]}</div>`).join('')}
function render(){const v=state.village||{},b=buildRec(),t=troopRec();$('village').textContent=`${v.name||'Dorf'}${v.x!=null?` (${v.x}|${v.y}) K${v.continent??'–'}`:''}`;$('world').textContent=state.page?.world||'–';$('updated').textContent=state.capturedAt?new Date(state.capturedAt).toLocaleString('de-DE'):'–';for(const k of ['wood','clay','iron','storage'])$(k).textContent=fmt(state.resources?.[k]);$('pop').textContent=`${fmt(state.population?.current)} / ${fmt(state.population?.max)}`;$('nextBuild').textContent=b[0];$('buildWhy').textContent=b[1];$('troop').textContent=t[0];$('troopWhy').textContent=t[1];const h=qSecs()/3600;$('night').textContent=h>=7?'Nacht vollständig abgedeckt':`Nur ${h.toFixed(1).replace('.',',')} Std. abgedeckt`;$('queueDuration').textContent=dur(qSecs());$('queue').innerHTML=(state.buildQueue||[]).map(x=>`<li><strong>${x.building}${x.targetLevel?' '+x.targetLevel:''}</strong><span>${x.remainingText||dur(x.remainingSeconds)}</span></li>`).join('')||'<li><strong>Keine Bauschleife</strong><span>–</span></li>';$('buildings').innerHTML=Object.entries(state.buildings||{}).sort((a,b)=>a[0].localeCompare(b[0],'de')).map(([n,l])=>`<div><span>${n}</span><strong>${l}</strong></div>`).join('');$('raw').value=JSON.stringify(state,null,2);$('diagnostics').textContent=JSON.stringify(state.diagnostics||{},null,2);status()}
function importHash(){if(!location.hash.startsWith('#import='))return;try{save(JSON.parse(decodeURIComponent(location.hash.slice(8))));history.replaceState(null,'',location.pathname+location.search)}catch(e){console.error(e)}}
$('openGame').onclick=()=>location.href=`https://${state.page?.world||'de256'}.die-staemme.de/game.php?screen=overview`;$('importJson').onclick=()=>{try{save(JSON.parse($('raw').value))}catch{alert('Ungültiges JSON')}};$('clear').onclick=()=>{localStorage.removeItem(KEY);location.reload()};
state=load()||{schemaVersion:5,page:{world:'de256'},village:{name:'Noch keine Daten'},resources:{},population:{},production:{},buildings:{},buildQueue:[],units:{},effects:[],completeness:{village:false,resources:false,population:false,production:false,buildings:false,buildQueue:false,units:false,effects:false}};render();importHash();addEventListener('hashchange',importHash);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
