// ==UserScript==
// @name         Stämme Coach Aktualisieren
// @namespace    staemme-coach
// @version      0.5.0
// @description  Liest Dorfdaten und öffnet den Stämme Coach.
// @match        https://*.die-staemme.de/game.php*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
(function(){
'use strict';
const COACH="https://gamingnerdssuedtirol-ctrl.github.io/staemme-coach/", BTN='staemme-coach-update-button';
const clean=v=>String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const num=v=>{if(v==null||v==='')return null;const n=parseInt(clean(v).replace(/\./g,'').replace(/[^\d-]/g,''),10);return Number.isFinite(n)?n:null};
const firstNum=(doc,sels)=>{for(const s of sels){const e=doc.querySelector(s);if(!e)continue;for(const v of [e.textContent,e.dataset?.value,e.dataset?.amount,e.value]){const n=num(v);if(n!==null)return n}}return null};
const gd=()=>window.game_data||{};
const sec=v=>{const m=clean(v).match(/(?:(\d+):)?(\d{1,2}):(\d{2})/);return m?(+m[1]||0)*3600+(+m[2]||0)*60+(+m[3]||0):null};
const urlFor=s=>{const u=new URL(location.href);u.searchParams.set('screen',s);u.searchParams.delete('intro');return u.href};
const fetchDoc=async s=>{const r=await fetch(urlFor(s),{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(s+' HTTP '+r.status);return new DOMParser().parseFromString(await r.text(),'text/html')};
function visibleResources(){const v=gd().village||{};return {wood:firstNum(document,['#wood','[data-resource="wood"]'])??num(v.wood),clay:firstNum(document,['#stone','[data-resource="stone"]'])??num(v.stone)??num(v.clay),iron:firstNum(document,['#iron','[data-resource="iron"]'])??num(v.iron),storage:firstNum(document,['#storage','[data-resource="storage"]'])??num(v.storage_max)??num(v.storage)}}
function visibleVillage(){const g=gd(),v=g.village||{},u=new URL(location.href),wm=location.hostname.match(/^([a-z]+\d+)\./i),body=clean(document.body?.textContent),cm=body.match(/\((\d{3})\|(\d{3})\)\s*K(\d+)/i);let name=clean(v.name);if(!name){for(const s of ['#menu_row2 .village-name','#menu_row2 b','#mobileHeader .village-name','[data-village-name]']){const e=document.querySelector(s),c=clean(e?.dataset?.villageName||e?.textContent);if(c&&!c.includes('Laden')){name=c.replace(/\(\d{3}\|\d{3}\).*$/,'').replace(/^.*?«\s*/,'').trim();if(name)break}}}return {world:g.world||wm?.[1]||null,villageId:String(v.id||u.searchParams.get('village')||'')||null,village:{id:String(v.id||u.searchParams.get('village')||'')||null,name:name||'Dorf',x:num(v.x)??(cm?+cm[1]:null),y:num(v.y)??(cm?+cm[2]:null),continent:cm?+cm[3]:null}}}
function population(doc=document){const v=gd().village||{};let current=firstNum(doc,['#pop_current'])??num(v.pop)??num(v.population),max=firstNum(doc,['#pop_max'])??num(v.pop_max)??num(v.population_max);if(current===null||max===null){const m=clean(doc.body?.textContent).match(/(\d[\d.]*)\s*\/\s*(\d[\d.]*)/);if(m){current=current??num(m[1]);max=max??num(m[2])}}return {current,max}}
function production(doc){const b=clean(doc.body?.textContent),get=r=>{const m=b.match(r);return m?num(m[1]):null};return {woodPerHour:get(/Holz\s+([\d.]+)\s+pro Stunde/i),clayPerHour:get(/Lehm\s+([\d.]+)\s+pro Stunde/i),ironPerHour:get(/Eisen\s+([\d.]+)\s+pro Stunde/i)}}
const bmap={main:'Hauptgebäude',barracks:'Kaserne',stable:'Stall',garage:'Werkstatt',smith:'Schmiede',place:'Versammlungsplatz',market:'Marktplatz',wood:'Holzfäller',stone:'Lehmgrube',iron:'Eisenmine',farm:'Bauernhof',storage:'Speicher',hide:'Versteck',wall:'Wall',snob:'Adelshof'};
function buildings(doc){const out={};for(const [code,name] of Object.entries(bmap)){for(const n of [doc.querySelector('#main_buildrow_'+code),doc.querySelector('[data-building="'+code+'"]'),doc.querySelector('#building_'+code),doc.querySelector('a[href*="screen='+code+'"]')?.closest('tr,div')].filter(Boolean)){const t=clean(n.textContent),m=t.match(/(?:Stufe|Level)\s*(\d+)/i)||t.match(/\((\d+)\)/)||t.match(/\b(\d+)\b/);if(m){out[name]=+m[1];break}}}return out}
function queue(doc){const out=[],seen=new Set(),roots=[doc.querySelector('#buildqueue'),doc.querySelector('.buildqueue'),doc.querySelector('#content_value')].filter(Boolean);for(const r of roots)for(const n of r.querySelectorAll('tr,.lit-item,.queue-item,.buildorder')){const t=clean(n.textContent),bm=t.match(/(Hauptgebäude|Kaserne|Stall|Werkstatt|Schmiede|Versammlungsplatz|Marktplatz|Holzfäller(?:lager)?|Lehmgrube|Eisenmine|Bauernhof|Speicher|Versteck|Wall|Adelshof)(?:\s*\(Stufe\s*(\d+)\))?/i),tm=t.match(/(?:(\d+):)?\d{1,2}:\d{2}/);if(!bm||!tm)continue;const b=bm[1].replace('Holzfällerlager','Holzfäller'),k=b+'|'+tm[0];if(seen.has(k))continue;seen.add(k);out.push({building:b,targetLevel:bm[2]?+bm[2]:null,remainingText:tm[0],remainingSeconds:sec(tm[0])})}return out}
function units(doc){const b=clean(doc.body?.textContent),p={spear:/(\d[\d.]*)\s+Speerträger/i,sword:/(\d[\d.]*)\s+Schwertkämpfer/i,axe:/(\d[\d.]*)\s+Axtkämpfer/i,spy:/(\d[\d.]*)\s+Späher/i,light:/(\d[\d.]*)\s+Leichte Kavallerie/i,heavy:/(\d[\d.]*)\s+Schwere Kavallerie/i,ram:/(\d[\d.]*)\s+Rammböcke?/i,catapult:/(\d[\d.]*)\s+Katapulte?/i},o={};for(const[k,r]of Object.entries(p)){const m=b.match(r);o[k]=m?num(m[1]):null}return o}
const merge=(...sets)=>{const o={spear:null,sword:null,axe:null,spy:null,light:null,heavy:null,ram:null,catapult:null};for(const s of sets)for(const[k,v]of Object.entries(s||{}))if(v!=null)o[k]=v;return o};
const effects=doc=>[...new Set([...clean(doc.body?.textContent).matchAll(/([+-]\d+\s*%\s+(?:Baugeschwindigkeit|Holzproduktion|Lehmproduktion|Eisenproduktion))/gi)].map(m=>m[1]))];
async function update(){const btn=document.getElementById(BTN);btn.disabled=true;btn.textContent='Coach wird aktualisiert …';try{const resources=visibleResources(),meta=visibleVillage(),pop=population(document),[ov,main,bar,sta]=await Promise.all([fetchDoc('overview'),fetchDoc('main'),fetchDoc('barracks'),fetchDoc('stable')]),b=buildings(main),q=queue(ov),prod=production(ov),u=merge(units(document),units(ov),units(bar),units(sta)),eff=effects(ov),count={};for(const x of q)if(x.targetLevel==null&&b[x.building]!=null){count[x.building]=(count[x.building]||0)+1;x.targetLevel=b[x.building]+count[x.building]}const complete={village:Boolean(meta.world)&&Number.isFinite(meta.village.x)&&Number.isFinite(meta.village.y),resources:['wood','clay','iron'].every(k=>Number.isFinite(resources[k])),population:Number.isFinite(pop.current)&&Number.isFinite(pop.max),production:['woodPerHour','clayPerHour','ironPerHour'].every(k=>Number.isFinite(prod[k])),buildings:Object.keys(b).length>=8,buildQueue:Array.isArray(q),units:['spear','sword','axe','spy','light'].some(k=>Number.isFinite(u[k])),effects:Array.isArray(eff)};const data={schemaVersion:5,capturedAt:new Date().toISOString(),page:{world:meta.world,villageId:meta.villageId,screen:'multi',url:location.href},village:meta.village,villageKey:meta.villageId||[meta.world,meta.village.x,meta.village.y].filter(v=>v!==null).join('-'),resources,population:pop,production:prod,buildings:b,buildQueue:q,units:u,effects:eff,completeness:complete,diagnostics:{resourcesSource:'visible-page/game_data',buildingsFound:Object.keys(b).length,queueEntries:q.length,unitsFound:Object.values(u).filter(Number.isFinite).length}};location.href=COACH+'#import='+encodeURIComponent(JSON.stringify(data))}catch(e){console.error(e);alert('Coach-Aktualisierung fehlgeschlagen: '+e.message);btn.disabled=false;btn.textContent='Coach aktualisieren'}}
function add(){if(document.getElementById(BTN))return;const b=document.createElement('button');b.id=BTN;b.textContent='Coach aktualisieren';Object.assign(b.style,{position:'fixed',right:'12px',bottom:'18px',zIndex:'99999',padding:'13px 17px',border:'2px solid #f5d6a5',borderRadius:'12px',background:'#7b2d0b',color:'#fff',fontWeight:'800',fontSize:'15px',boxShadow:'0 4px 14px rgba(0,0,0,.35)'});b.onclick=update;document.body.appendChild(b)}add();
})();
